### PR TITLE
Fix MongoDB Seed Script

### PR DESCRIPTION
**Pull request by TaylorBeeston**
See #9

### CODE REVIEW

**Comment by Fabianopb** [comment]
Thanks for this update @TaylorBeeston ! 🚀 

I wonder why Travis has this pending status, though... 🤔

**Comment by TaylorBeeston** [comment]
No problem! I'm not 100% sure what's going on there, but it looks like GH just didn't pick up that [Travis actually finished running (and passed)](https://travis-ci.com/github/Fabianopb/create-fullstack-react-app/builds/165849317)

**Comment by Fabianopb** [comment]
Alright, let's merge that and see if everything is green on `master`, then I'll make a new release! Thanks again! 🙂

**Comment by TaylorBeeston** [comment]
No problem!
I don't know if this is the right place to ask this (I'm still a little new to contributing), but I'm curious about how you feel about feature requests and the general scope of this project. For example, the newly created app doesn't come with eslint/prettier set up out of the box. Is that intentional, or would you be open to adding it with possibly another prompt asking which style guide to follow?

**Comment by Fabianopb** [comment]
That's ok! Usually feature requests can be created by opening a new issue.

But I can tell quickly in this case that this was intentionally left out so the bootstrapped applications wouldn't be too opinionated and easier to maintain.

**Pull request merged**
